[template]

include = [
    "Cargo.toml",
    "node/src/chain_spec.rs",
    "node/src/cli.rs",
    "node/src/command.rs",
    "node/src/rpc.rs",
    "node/src/service.rs",
    "runtime/Cargo.toml",
    "runtime/src/lib.rs",
    "network.toml",
]
exclude = [
    "Cargo.lock",
    "node/build.rs",
    "node/src/main.rs",
    "runtime/build.rs",
    "runtime/src/configs/*",
    "runtime/src/weights/*",
    "runtime/src/apis.rs",
    "runtime/src/benchmarks.rs",
    "target/*",
    "LICENSE",
    "README.md",
    "rust-toolchain.toml",
    ".gitignore",
    ".github",
    ".git",
    "cargo-generate.toml"
]
